### ISSUE TITLE
spam can cause doorman/xania lockup

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#102]
With e.g. #97  you can get a xania/doorman lockup.

Xania gets stuck in a syscall:

```
(gdb) bt
#0  0x00007f696ad81297 in __libc_write (fd=5, buf=0x7ffc6a078af0, nbytes=12) at ../sysdeps/unix/sysv/linux/write.c:26
#1  0x0000562652adfbb0 in __interceptor_write.part.0 ()
#2  0x0000562652bdbbc3 in SendPacket (p=0x7ffc6a078af0, extra=0x562652e41ea0) at ../src/comm.cpp:100
#3  0x0000562652be68f2 in write_to_descriptor (desc=0, txt=0x562652e41ea0 "\n\r*** PUT A LID ON IT!!! ***\n\r", length=30) at ../src/comm.cpp:892
```

and doorman is stuck too:

```
0x00007f46f5807457 in __GI___writev (fd=4, iov=0x7ffe87a10fe0, iovcnt=3) at ../sysdeps/unix/sysv/linux/writev.c:26
26	../sysdeps/unix/sysv/linux/writev.c: No such file or directory.
(gdb) bt
#0  0x00007f46f5807457 in __GI___writev (fd=4, iov=0x7ffe87a10fe0, iovcnt=3) at ../sysdeps/unix/sysv/linux/writev.c:26
#1  0x0000563c757c3829 in writev ()
#2  0x0000563c75913758 in Fd::writev (this=0x7ffe87a12350, io_vecs=...) at ../src/doorman/Fd.cpp:20
#3  0x0000563c75944f0d in Fd::write_many<tagPacket&, std::basic_string_view<char, std::char_traits<char> >&, std::basic_string_view<char, std::char_traits<char> > > (this=0x7ffe87a12350)
    at ../src/doorman/Fd.hpp:70
#4  0x0000563c75940d0e in Xania::on_client_message (this=0x7ffe87a12278, channel=..., message="?R\265k\203\033XW\353\337v\343\327\330\374f", <incomplete sequence \326>) at ../src/doorman/Xania.cpp:174
#5  0x0000563c758d90fe in Channel::on_line (this=0x613000000c80, line="?R\265k\203\033XW\353\337v\343\327\330\374f", <incomplete sequence \326>) at ../src/doorman/Channel.cpp:180
```

Good ol' deadlock with a too-small pipe between processes...

**Comment by mattgodbolt** [comment]
Probably one or both should mark the pipe as non-blocking and handle the "zomg the other end is overwhelmed". As well as other mitigation for #46
