### ISSUE TITLE
crash bug in death_cry()

### ISSUE THREAD

**Issue by snellers** [mattgodbolt/xania#169]
```
xania@mud:~$ gdb releases/xania-474/bin/xania releases/xania-474/area/core 
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from releases/xania-474/bin/xania...
(No debugging symbols found in releases/xania-474/bin/xania)
[New LWP 226956]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/xania/releases/current/bin/xania'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007f0ab7bbee95 in __vfprintf_internal (s=s@entry=0x7ffe31ea62d0, format=format@entry=0x7f0ab77a04b3 "the guts of %s", ap=ap@entry=0x7ffe31ea6450, mode_flags=mode_flags@entry=2) at vfprintf-internal.c:1688
#2  0x00007f0ab7bd211a in __vsnprintf_internal (string=0x7ffe31ea6590 "the guts of \230\324\001\226\231g\352\061\376\177", maxlen=<optimized out>, format=0x7f0ab77a04b3 "the guts of %s", args=args@entry=0x7ffe31ea6450, mode_flags=2) at vsnprintf.c:114
#3  0x00007f0ab7c73e41 in ___snprintf_chk (s=<optimized out>, maxlen=<optimized out>, flag=<optimized out>, slen=<optimized out>, format=<optimized out>) at snprintf_chk.c:38
#4  0x000056115fb7822b in death_cry(CHAR_DATA*) ()
#5  0x000056115fb78700 in raw_kill(CHAR_DATA*) ()
#6  0x000056115fb7c365 in damage(CHAR_DATA*, CHAR_DATA*, int, int, int) ()
#7  0x000056115fba37fe in do_cast(CHAR_DATA*, char const*) ()
#8  0x000056115fb8d4c3 in interpret(CHAR_DATA*, char const*) ()
#9  0x000056115fb6cdd5 in game_loop_unix(Fd) ()
#10 0x000056115fb64ad4 in main ()
(gdb) 2020-08-23 20:44:45.867344659 :: TICK

```

**Comment by snellers** [comment]
To repro: kill any NPC that can drop body parts.
