### ISSUE TITLE
crash bug in  do_flee?

### ISSUE THREAD

**Issue by snellers** [mattgodbolt/xania#223]
```
/dev/xania/src/act_move.cpp:127:72: runtime error: index -1 out of bounds for type 'short int [11]'
=================================================================
==5639==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5555570d8b9e at pc 0x555556c308f8 bp 0x7fffffffc4f0 sp 0x7fffffffc4e0
READ of size 2 at 0x5555570d8b9e thread T0
    #0 0x555556c308f7 in move_char(Char*, Direction) /dev/xania/src/act_move.cpp:127
    #1 0x555556886f77 in do_flee(Char*) /dev/xania/src/fight.cpp:2631
    #2 0x55555686717e in damage(Char*, Char*, int, int, int) /dev/xania/src/fight.cpp:916
    #3 0x5555569c0c46 in spell_acid_blast(int, int, Char*, void*) /dev/xania/src/magic.cpp:605
    #4 0x555556ab63e7 in spec_cast_mage(Char*) /dev/xania/src/special.cpp:499
```

**Comment by snellers** [comment]
This was due to invalid sector type in some rooms, largely resolved by a397cb33bcf497bb.
